on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: lubuntu # Ou o label que seu runner utiliza (ex: ubuntu-latest)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Tag Name
        id: tag_name
        run: |
          # Gera uma tag baseada na data e hora (ex: 2026.02.16-1030)
          # Você também pode ler a versão de um arquivo (package.json, VERSION, etc)
          #echo "tag=v$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
          VERSION_BASE="v3.0"
          tag="${VERSION_BASE}.${{ github.run_number }}"
          echo "Criando release para a tag: $tag"
          echo $tag >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

      - name: Create Release
        uses: https://github.com/softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_name.outputs.tag }}
          name: Release ${{ steps.tag_name.outputs.tag }}
          body:  "Build automatizada nº ${{ github.run_number }} realizada em $(date +'%d/%m/%Y %H:%M')"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
